version: "3"
services:
    ngrok-alice:
        image: wernight/ngrok
        command: ngrok http alice:3000 --log stdout
    alice:
        build: .
        image: mediator-lab
        ports:
            - "3000:3000"
            - "3001:3001"
        environment:
            NGROK_NAME: ngrok-alice
        command: start --arg-file configs/alice.yml
    ngrok-bob:
        image: wernight/ngrok
        command: ngrok http bob:3004 --log stdout
    bob:
        build: .
        image: mediator-lab
        ports:
            - "3004:3004"
            - "3005:3005"
        environment:
            NGROK_NAME: ngrok-bob
        command: start --arg-file configs/bob.yml
    ngrok-mediator:
        image: wernight/ngrok
        command: ngrok http mediator:3002 --log stdout
    mediator:
        build: .
        image: mediator-lab
        ports:
            - "3002:3002"
            - "3003:3003"
        environment:
            NGROK_NAME: ngrok-mediator
        command: start --arg-file configs/mediator.yml
